stages:
  - deploy

create_and_push_image:
  stage: deploy
  image: docker:20.10.17-alpine3.16
  environment:
    name: nexus
  tags:
    - default
    - dockerbuilder
  variables:
    IMAGE_NAME: shogun-docker.terrestris.de/shogun-docs
    IMAGE_TAG: main
  rules:
    # Run for main branch and tags only
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_REF_NAME =~ /^\d\.\d\.\d/
      variables:
        IMAGE_TAG: $CI_COMMIT_REF_NAME
  script:
    - mkdir -p $HOME/.docker/
    - echo "$DOCKER_AUTH_CONFIG" > $HOME/.docker/config.json
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
