FROM node:20.12.1-alpine3.19 AS build

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm ci

COPY . ./
RUN rm -rf /app/docs/gis-client

COPY docusaurus.admin.config.js ./docusaurus.config.js

RUN npm run build

FROM nginx:1.25.3-alpine-slim

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
